// app/layout.tsx
import { Metadata } from "next";
import React from "react";
import "../globals.css";
import { Providers } from "../utilsFunctions/Providers/NextUIProvider";
import ReduxProvider from "../utilsFunctions/Providers/ReduxProvider";
export const metadata: Metadata = {
  title: "Torus 9X App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="light">
      <body>
        <Providers>
          <ReduxProvider>
            <div className="w-full">{children}</div>
          </ReduxProvider>
        </Providers>
      </body>
    </html>
  );
}
