// app/layout.tsx
import { Metadata } from "next";
import React from "react";
import { Providers } from "@/app/utilsFunctions/Providers/NextUIProvider";
import ReduxProvider from "@/app/utilsFunctions/Providers/ReduxProvider";
import "../../globals.css";
import Topbar from "../../componentsLibrary/LayOutComponents/Topbar";
import SideNav from "../../componentsLibrary/LayOutComponents/SideNav";
import Footer from "../../componentsLibrary/LayOutComponents/Footer";
export const metadata: Metadata = {
  title: "Torus 9X App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="light">
      <body>
        <Providers>
          <ReduxProvider>
            {" "}
            <div className="flex flex-col w-full h-full">
              <div>
                <Topbar />
              </div>
              <div className="flex w-full h-full">
                <div>
                  <SideNav />
                </div>
                <div className="w-full">{children}</div>
              </div>
              <div>
                <Footer />
              </div>
            </div>
          </ReduxProvider>
        </Providers>
      </body>
    </html>
  );
}
